package com.lbg.ib.api.sales.docupload.util;

public enum SalsaEndpoints {
    
    GET_CASE_ENDPOINT, CREATE_CASE_ENDPOINT, REF_DATA_ENDPOINT, UPDATE_CASE_ENDPOINT, JWT_VALIDATE_ENPOINT, JWT_CREATE_ENDPOINT, RETRIEVE_DOC_ENDPOINT, CREATE_DOC_ENDPOINT, DELETE_DOC_ENDPOINT, GET_PROCESS_ENDPOINT, REQUEST_OTP_ENDPOINT, RETRIEVE_PARTY_DETAILS_ENDPOINT, Q226_ENDPOINT, CARD_ORDER_CMAS_ENDPOINT, GET_CASES_ENDPOINT, ASSIGN_CASE_ENDPOINT, RECORD_OUTCOME_ENDPOINT, Q227_ENDPOINT, APTDA_ENDPOINT, SEARCH_CASE_ENDPOINT

}
